info:
  user:
    defaultPassword: 123456

server:
  servlet:
    context-path: /
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
#    username: jfmm
#    password: jfmm2019
#    url: jdbc:mysql://192.168.2.99:3306/db_jfmm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true

    username: jfmm
    password: jfmm2019
    url: jdbc:mysql://192.168.2.99:3306/db_jfmm?useUnicode=true&characterEncoding=utf8&autoReconnect=true&&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMulQueries=true&nullCatalogMeansCurrent=true&serverTimezone=GMT%2b8&allowMultiQueries=true
#    url: jdbc:mysql://192.168.2.99:3306/db_jfmm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/db_jfmm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.jinfei.jfmm.model


# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /401
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

logging:
  level:
    com.jinfei.jfmm.dao: DEBUG
#    org.activiti.engine.impl.persistence.entity: trace